In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import mean_absolute_error, mean_squared_error,root_mean_squared_error, r2_score
import joblib
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Loading data
path = "C:\\Users\\123\\Desktop\\python project for data analitycs\\Data\\Advertising.csv"

data = pd.read_csv(path)

In [4]:
data.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [6]:
df = data.iloc[:,1:]

In [7]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

In [10]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.dtypes

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [18]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [19]:
x = df.drop("Sales",axis=1)
y = df["Sales"]

In [20]:
x.shape, y.shape

((200, 3), (200,))

In [21]:
# Splitting data into test train case

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 45)

In [22]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 3), (40, 3), (160,), (40,))

In [23]:
scl = StandardScaler()

In [24]:
x_train_scl = scl.fit_transform(x_train)
x_test_scl = scl.transform(x_test)

In [25]:
x_train_scl

array([[ 4.64728208e-01, -1.41321171e-01, -4.12487431e-01],
       [ 8.96986607e-01, -1.30938814e+00, -8.07552068e-01],
       [-1.17093757e+00,  1.83879293e-01, -4.79071359e-01],
       [-6.08980040e-02, -5.72709541e-01, -9.36280994e-01],
       [ 1.52520215e+00,  1.71033045e+00,  4.66420412e-01],
       [-6.20506931e-02, -5.85983029e-01, -2.52686005e-01],
       [-1.10984505e+00,  1.58423231e+00, -1.01174278e+00],
       [-8.52795390e-01, -4.73158379e-01,  4.22031127e-01],
       [ 1.34538265e+00,  1.29885231e+00,  1.03904219e+00],
       [-8.78154549e-01,  1.41831371e+00,  1.91206845e-01],
       [ 1.64853988e+00,  1.31876254e+00,  1.79809896e+00],
       [ 1.25893097e+00, -1.21410938e-01, -5.73731509e-02],
       [ 1.19668576e+00,  4.69259291e-01, -4.87949216e-01],
       [ 7.17167113e-01, -1.18992675e+00, -5.27899572e-01],
       [-1.16978488e+00,  2.36973246e-01,  1.69012203e-01],
       [-3.29474556e-01, -1.02400814e+00, -3.63659218e-01],
       [-5.85926259e-02, -1.39566582e+00

In [26]:
x_test_scl

array([[ 0.35176468, -0.04177001,  0.00921078],
       [-1.3576732 ,  0.65508813, -0.5323385 ],
       [ 0.66760148, -0.0550435 ,  0.01364971],
       [ 0.76327468,  1.75678766,  0.28442434],
       [ 1.36382568, -1.3027514 , -0.52346064],
       [-0.54272203, -1.03064489, -1.06944885],
       [ 0.3079625 ,  1.09974999,  0.28442434],
       [-0.78593942,  0.23697325, -0.39917065],
       [ 0.07973006,  1.20593789,  1.20772147],
       [-1.37726891,  0.1706058 ,  0.53300434],
       [-1.2412516 ,  1.0267458 ,  1.5228854 ],
       [-1.15134186,  0.17724255, -0.47463243],
       [ 0.27453451, -1.06382861, -0.82086885],
       [ 1.39494828, -0.20768861, -1.37573492],
       [ 1.09179106, -0.5063421 , -0.17722422],
       [-1.01878261, -1.15674303, -0.07068994],
       [ 0.35868081, -0.51297884, -1.28251742],
       [-0.97959119, -0.73862814,  0.52412648],
       [ 0.83243602,  1.37849324, -0.18166315],
       [-1.21128169,  1.1926644 , -1.13159385],
       [ 0.86701669,  0.68827185,  0.612

In [27]:
Lr = LinearRegression()

In [28]:
Lr.fit(x_train_scl,y_train)

LinearRegression()

In [29]:
Lr.intercept_

np.float64(13.87125)

In [30]:
Lr.coef_

array([ 4.07686894,  2.76432822, -0.10958854])

In [31]:
y_pred = Lr.predict(x_test_scl)

In [32]:
pd.DataFrame({"Y_pred":y_pred,"Y_test":y_test})

Y_pred  Y_test
45   15.188873    14.9
72   10.205411     8.8
40   16.439320    16.6
58   21.808189    23.8
25   15.887521    12.0
13    8.926802     9.7
153  18.135673    19.0
80   11.365894    11.8
3    17.397555    18.5
44    8.669504     8.5
134  11.482201    10.8
149   9.719351    10.1
173  12.139678    11.7
33   19.134917    17.4
62   16.942065    15.7
182   6.527936     8.7
112  14.056052    14.1
129   7.778336     9.7
69   21.095499    22.3
190  12.353939    10.8
133  19.241405    19.6
172   7.511594     7.6
35   17.357531    12.8
157  10.145578    10.1
187  17.142930    17.3
10    7.038274     8.6
104  20.446466    20.7
177  12.243723    11.7
26   15.015156    15.0
171  14.319856    14.5
147  23.188599    25.4
0    20.397088    22.1
109  19.896170    19.8
194  16.522626    17.3
151   9.976042    11.6
82   10.090430    11.3
64   16.858068    18.0
169  18.259486    15.0
4    13.179382    12.9
28   19.538061    18.9

In [41]:
# Model evaluation or performance matrix
print()
print(f"Mean Squared Error : {mean_squared_error(y_test,y_pred)}")
print()
print("="*60)
print()
print(f"Root Mean Squared Error : {root_mean_squared_error(y_test,y_pred)}")
print()
print("="*60)
print()
print(f"Mean Absolute error : {mean_absolute_error(y_test,y_pred)}")
print()
print("="*60)
print()
print(f"R2 Score : {r2_score(y_test,y_pred)}")
print()
print("="*60)
print()
r2 = r2_score(y_test,y_pred)
n = x_test.shape[0]
k = x_test.shape[1]
adjusted_r2 = 1 - ((1-r2)*(n-1))/(n-k-1)
print(f"Adjusted R2 : {adjusted_r2}") 


Mean Squared Error : 2.256494247280935


Root Mean Squared Error : 1.5021631892976657


Mean Absolute error : 1.0788802763848646


R2 Score : 0.8955882331233612


Adjusted R2 : 0.886887252550308


In [42]:
joblib.dump(Lr, "linear.pkl")

['linear.pkl']

In [43]:
new_data = [[205,33,77]]

In [47]:
LR = joblib.load("linear.pkl")

In [45]:
joblib.dump(scl,"Scaler.pkl")

['Scaler.pkl']

In [46]:
joblib.load("Scaler.pkl")

StandardScaler()

In [48]:
new_record = scl.transform(new_data)

In [49]:
LR.predict(new_record)

array([18.29898968])

In [50]:
# Applying reglarization on model

l1 = Lasso()
l2 = Ridge()
En = ElasticNet()

In [51]:
l1.fit(x_train_scl,y_train)

Lasso()

In [52]:
l1.intercept_

np.float64(13.87125)

In [53]:
l1.coef_

array([3.12845271, 1.78319971, 0.        ])

In [54]:
y_pred_l1 = l1.predict(x_test_scl)

In [55]:
# Model evaluation or performance matrix
print()
print(f"Mean Squared Error : {mean_squared_error(y_test,y_pred_l1)}")
print()
print("="*60)
print()
print(f"Root Mean Squared Error : {root_mean_squared_error(y_test,y_pred_l1)}")
print()
print("="*60)
print()
print(f"Mean Absolute error : {mean_absolute_error(y_test,y_pred_l1)}")
print()
print("="*60)
print()
print(f"R2 Score : {r2_score(y_test,y_pred_l1)}")
print()
print("="*60)
print()
r2_l1 = r2_score(y_test,y_pred_l1)
n = x_test.shape[0]
k = x_test.shape[1]
adjusted_r2 = 1 - ((1-r2_l1)*(n-1))/(n-k-1)
print(f"Adjusted R2 : {adjusted_r2}") 


Mean Squared Error : 3.81081862922139


Root Mean Squared Error : 1.9521318165588588


Mean Absolute error : 1.474397807219202


R2 Score : 0.8236670415610957


Adjusted R2 : 0.8089726283578537


In [56]:
# Ridge regression
l2.fit(x_train_scl,y_train)

Ridge()

In [57]:
l2.intercept_

np.float64(13.87125)

In [58]:
l2.coef_

array([ 4.05174647,  2.74479232, -0.09907862])

In [59]:
y_pred_l2 = l2.predict(x_test_scl)

In [60]:
# Model evaluation or performance matrix
print()
print(f"Mean Squared Error : {mean_squared_error(y_test,y_pred_l2)}")
print()
print("="*60)
print()
print(f"Root Mean Squared Error : {root_mean_squared_error(y_test,y_pred_l2)}")
print()
print("="*60)
print()
print(f"Mean Absolute error : {mean_absolute_error(y_test,y_pred_l2)}")
print()
print("="*60)
print()
print(f"R2 Score : {r2_score(y_test,y_pred_l2)}")
print()
print("="*60)
print()
r2_l2 = r2_score(y_test,y_pred_l2)
n = x_test.shape[0]
k = x_test.shape[1]
adjusted_r2 = 1 - ((1-r2_l2)*(n-1))/(n-k-1)
print(f"Adjusted R2 : {adjusted_r2}") 


Mean Squared Error : 2.242072898850527


Root Mean Squared Error : 1.4973553014734102


Mean Absolute error : 1.0791150813362156


R2 Score : 0.8962555330609423


Adjusted R2 : 0.8876101608160208


In [61]:
En.fit(x_train_scl,y_train)

ElasticNet()

In [62]:
En.intercept_

np.float64(13.87125)

In [63]:
En.coef_

array([2.42826611, 1.54949022, 0.00935345])

In [64]:
y_pred_en = En.predict(x_test_scl)

In [65]:
# Model evaluation or performance matrix
print()
print(f"Mean Squared Error : {mean_squared_error(y_test,y_pred_en)}")
print()
print("="*60)
print()
print(f"Root Mean Squared Error : {root_mean_squared_error(y_test,y_pred_en)}")
print()
print("="*60)
print()
print(f"Mean Absolute error : {mean_absolute_error(y_test,y_pred_en)}")
print()
print("="*60)
print()
print(f"R2 Score : {r2_score(y_test,y_pred_en)}")
print()
print("="*60)
print()
r2_en = r2_score(y_test,y_pred_en)
n = x_test.shape[0]
k = x_test.shape[1]
adjusted_r2 = 1 - ((1-r2_en)*(n-1))/(n-k-1)
print(f"Adjusted R2 : {adjusted_r2}") 


Mean Squared Error : 5.423968914320369


Root Mean Squared Error : 2.3289415867128076


Mean Absolute error : 1.856515548378986


R2 Score : 0.7490238769673027


Adjusted R2 : 0.7281092000479112


In [67]:
joblib.dump(l1,"Lasso_1.pkl")
joblib.dump(l2,"Ridge_1.pkl")
joblib.dump(En,"ElasticNet_1.pkl")

['ElasticNet_1.pkl']

In [68]:
new_data = [[44,39,45]]

In [70]:
L1 = joblib.load("Lasso_1.pkl")
L2 = joblib.load("Ridge_1.pkl")
EN = joblib.load("ElasticNet_1.pkl")

In [71]:
new_rec_scl = scl.transform(new_data)

In [72]:
new_rec_scl

array([[-1.15941068,  1.05329278,  0.60846612]])

In [73]:
print("Prediction by lasso Model :", L1.predict(new_rec_scl))
print()
print("Prediction by Ridge Model :", L2.predict(new_rec_scl))
print()
print("Prediction by elasticnet :", EN.predict(new_rec_scl))

Prediction by lasso Model : [12.12231989]

Prediction by Ridge Model : [12.00439582]

Prediction by elasticnet : [12.69365046]
