In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, Lasso, Ridge, ElasticNet
from sklearn.metrics import accuracy_score, classification_report, roc_curve, roc_auc_score
import joblib
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Loading data set

path = "C:\\Users\\123\Desktop\\python project for data analitycs\\Data\\drug200.csv"

data = pd.read_csv(path)


In [3]:
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [4]:
df = data.copy()

In [5]:
# Encoding
le = LabelEncoder()

In [6]:
df["BP"] = le.fit_transform(df["BP"])
df["Cholesterol"] = le.fit_transform(df["Cholesterol"])
df["Drug"] = le.fit_transform(df["Drug"])
df["Sex"] = le.fit_transform(df["Sex"])

In [7]:
df.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0

In [8]:
df["Drug"].unique()

array([0, 3, 4, 1, 2])

In [9]:
data["Drug"].unique()

array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [10]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    int64  
 2   BP           200 non-null    int64  
 3   Cholesterol  200 non-null    int64  
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 9.5 KB


In [13]:
df.describe()

Age         Sex          BP  Cholesterol     Na_to_K        Drug
count  200.000000  200.000000  200.000000   200.000000  200.000000  200.000000
mean    44.315000    0.520000    0.910000     0.485000   16.084485    1.595000
std     16.544315    0.500854    0.821752     0.501029    7.223956    1.716305
min     15.000000    0.000000    0.000000     0.000000    6.269000    0.000000
25%     31.000000    0.000000    0.000000     0.000000   10.445500    0.000000
50%     45.000000    1.000000    1.000000     0.000000   13.936500    1.000000
75%     58.000000    1.000000    2.000000     1.000000   19.380000    4.000000
max     74.000000    1.000000    2.000000     1.000000   38.247000    4.000000

In [14]:
df.corr()["Drug"]

Age            0.041856
Sex            0.018239
BP             0.419397
Cholesterol    0.048415
Na_to_K       -0.689051
Drug           1.000000
Name: Drug, dtype: float64

In [15]:
x = df.drop("Drug",axis=1)
y = df["Drug"]

In [16]:
x.head()

Age  Sex  BP  Cholesterol  Na_to_K
0   23    0   0            0   25.355
1   47    1   1            0   13.093
2   47    1   1            0   10.114
3   28    0   2            0    7.798
4   61    0   1            0   18.043

In [17]:
y.head()

0    0
1    3
2    3
3    4
4    0
Name: Drug, dtype: int64

In [18]:
print("Shape of Feature data and Target data :", x.shape,y.shape)

Shape of Feature data and Target data : (200, 5) (200,)


In [19]:
# Spliting data into train test case

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2 , random_state = 40)

In [20]:
x_train.shape , x_test.shape , y_train.shape, y_test.shape

((160, 5), (40, 5), (160,), (40,))

In [21]:
scl = StandardScaler()

In [22]:
x_train_scl = scl.fit_transform(x_train)
x_test_scl = scl.transform(x_test)

In [33]:
Log_R = LogisticRegression()

In [34]:
Log_R.fit(x_train_scl,y_train)

LogisticRegression()

In [35]:
Log_R.intercept_

array([ 3.16200204, -1.50394664, -1.61067897, -0.38909073,  0.34171431])

In [36]:
y_pred = Log_R.predict(x_test_scl)

In [39]:
pd.DataFrame({"Y-Test":y_test,"Y-Pred":y_pred})[:10]

Y-Test  Y-Pred
96        0       0
5         4       4
116       4       4
35        4       4
183       0       0
160       4       4
54        2       2
134       0       0
90        0       0
191       1       1

In [40]:
accuracy_score(y_test,y_pred)

0.925

In [43]:
print("="*80)
print("Classification Metrics")
print()
print(classification_report(y_test,y_pred))
print("="*80)

Classification Metrics

              precision    recall  f1-score   support

           0       0.89      0.94      0.91        17
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         1
           4       0.91      0.83      0.87        12

    accuracy                           0.93        40
   macro avg       0.96      0.95      0.96        40
weighted avg       0.93      0.93      0.92        40



In [44]:
joblib.dump(Log_R,"Logistic_Reg1.pkl")

['Logistic_Reg1.pkl']

In [55]:
y_score = Log_R.predict_proba(x_test_scl)
y_score

array([[9.99999969e-01, 2.75320268e-10, 1.79056351e-08, 1.14908770e-08,
        1.72289214e-09],
       [3.34312919e-03, 2.01578308e-03, 7.49840675e-05, 1.64543860e-01,
        8.30022243e-01],
       [4.24679272e-03, 2.02674861e-05, 3.15551043e-04, 1.06186950e-03,
        9.94355519e-01],
       [6.97424010e-04, 6.14111475e-05, 4.48396800e-05, 1.25788387e-03,
        9.97938441e-01],
       [6.46032683e-01, 2.05724104e-01, 1.00058488e-01, 1.39293191e-02,
        3.42554060e-02],
       [1.43274888e-02, 1.32578191e-03, 1.75380175e-04, 1.59393113e-01,
        8.24778237e-01],
       [1.36737754e-02, 4.29686934e-02, 8.92516245e-01, 9.39099851e-03,
        4.14502879e-02],
       [9.68950241e-01, 1.29651507e-02, 1.00859058e-02, 7.88566576e-03,
        1.13036647e-04],
       [8.35359299e-01, 9.53157971e-05, 6.33650889e-04, 2.97290457e-02,
        1.34182689e-01],
       [1.08319998e-03, 8.96691141e-01, 4.93644425e-03, 9.59326477e-02,
        1.35656652e-03],
       [1.28325931e-02, 1.7453

In [23]:
# Applying reglarization on model
L1 = joblib.load("Lasso_1.pkl")
L2 = joblib.load("Ridge_1.pkl")
EN = joblib.load("ElasticNet_1.pkl")

In [24]:
L1.fit(x_train_scl,y_train)

Lasso()

In [25]:
L1.intercept_

np.float64(1.5875)

In [26]:
L1.coef_

array([ 0.        ,  0.        ,  0.        ,  0.        , -0.18334981])

In [27]:
y_pred_l1 = L1.predict(x_test_scl)

In [32]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,root_mean_squared_error, r2_score

In [33]:
# Model evaluation or performance matrix
print()
print(f"Mean Squared Error : {mean_squared_error(y_test,y_pred_l1)}")
print()
print("="*60)
print()
print(f"Root Mean Squared Error : {root_mean_squared_error(y_test,y_pred_l1)}")
print()
print("="*60)
print()
print(f"Mean Absolute error : {mean_absolute_error(y_test,y_pred_l1)}")
print()
print("="*60)
print()
print(f"R2 Score : {r2_score(y_test,y_pred_l1)}")
print()
print("="*60)
print()
r2_l1 = r2_score(y_test,y_pred_l1)
n = x_test.shape[0]
k = x_test.shape[1]
adjusted_r2 = 1 - ((1-r2_l1)*(n-1))/(n-k-1)
print(f"Adjusted R2 : {adjusted_r2}") 


Mean Squared Error : 2.5100238125144285


Root Mean Squared Error : 1.5843054669205774


Mean Absolute error : 1.4455018323858138


R2 Score : 0.14461382321127025


Adjusted R2 : 0.018821738389398268
