In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

In [4]:
# Loading Data
data = pd.read_csv("_MConverter.eu_Placement Data.csv")

In [5]:
data.head()

Unnamed: 0 grade  cgpa   iq  communication  technical_knowledge  placement
0           0     B  7.34  124              1                    7          0
1           1     D  8.88  112              1                    5          0
2           2     C  7.95   85              8                    8          0
3           3     B  6.42  103              8                    8          1
4           4     A  6.10   98              6                    9          1

In [6]:
df = data.iloc[:,1:]

In [7]:
df.head()

grade  cgpa   iq  communication  technical_knowledge  placement
0     B  7.34  124              1                    7          0
1     D  8.88  112              1                    5          0
2     C  7.95   85              8                    8          0
3     B  6.42  103              8                    8          1
4     A  6.10   98              6                    9          1

In [8]:
le = LabelEncoder()

In [9]:
df["grade"] = le.fit_transform(df["grade"])

In [10]:
df.head()

grade  cgpa   iq  communication  technical_knowledge  placement
0      1  7.34  124              1                    7          0
1      3  8.88  112              1                    5          0
2      2  7.95   85              8                    8          0
3      1  6.42  103              8                    8          1
4      0  6.10   98              6                    9          1

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   grade                500 non-null    int64  
 1   cgpa                 500 non-null    float64
 2   iq                   500 non-null    int64  
 3   communication        500 non-null    int64  
 4   technical_knowledge  500 non-null    int64  
 5   placement            500 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 23.6 KB


In [13]:
df.describe()

grade        cgpa          iq  communication  technical_knowledge  \
count  500.000000  500.000000  500.000000     500.000000           500.000000   
mean     1.110000    7.007540  109.786000       5.344000             5.626000   
std      0.967353    1.006612   17.363848       2.852707             2.810324   
min      0.000000    4.300000   80.000000       1.000000             1.000000   
25%      0.000000    6.350000   94.000000       3.000000             3.000000   
50%      1.000000    6.970000  110.000000       5.000000             6.000000   
75%      2.000000    7.662500  124.000000       8.000000             8.000000   
max      3.000000   10.000000  140.000000      10.000000            10.000000   

        placement  
count  500.000000  
mean     0.496000  
std      0.500485  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [14]:
df.isnull().sum()

grade                  0
cgpa                   0
iq                     0
communication          0
technical_knowledge    0
placement              0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
# defining feature X and target Y

x = df.drop("placement",axis = 1)
y = df["placement"]

In [18]:
x

grade  cgpa   iq  communication  technical_knowledge
0        1  7.34  124              1                    7
1        3  8.88  112              1                    5
2        2  7.95   85              8                    8
3        1  6.42  103              8                    8
4        0  6.10   98              6                    9
..     ...   ...  ...            ...                  ...
495      1  6.47  116              7                   10
496      1  6.51  126              8                    9
497      0  8.04  116              3                    6
498      3  7.68   91              5                    5
499      3  8.85  116              1                    3

[500 rows x 5 columns]

In [19]:
y

0      0
1      0
2      0
3      1
4      1
      ..
495    1
496    1
497    1
498    0
499    0
Name: placement, Length: 500, dtype: int64

In [23]:
#splitting data into test train case

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [24]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((400, 5), (100, 5), (400,), (100,))

In [25]:
x_train.head()

grade  cgpa   iq  communication  technical_knowledge
249      2  5.35  130              1                    9
433      0  8.07   81              7                    7
19       0  7.62  115              1                    3
322      1  4.92   85              2                    1
332      0  6.64   97             10                    6

In [26]:
y_train.head()

249    0
433    1
19     0
322    0
332    1
Name: placement, dtype: int64

In [27]:
# Standardization( mean = 0 and sd = 1)

scaler = StandardScaler()

In [28]:
x_train_scl = scaler.fit_transform(x_train)
x_test_scl = scaler.fit_transform(x_test)

In [30]:
x_train_scl

array([[ 0.91303697, -1.64276431,  1.18743074, -1.51953767,  1.19880545],
       [-1.14451114,  1.07436486, -1.66683005,  0.57397003,  0.48997739],
       [-1.14451114,  0.62483981,  0.31367744, -1.51953767, -0.92767872],
       ...,
       [-0.11573708,  1.03440708, -0.09407411,  0.92288798,  0.84439142],
       [ 0.91303697,  1.41400601,  0.37192766, -0.12386587,  1.19880545],
       [-0.11573708,  1.69371048, -1.08432785, -1.51953767,  0.84439142]],
      shape=(400, 5))

In [33]:
x_test_scl

array([[-0.10599979, -0.80210744,  0.02939689, -0.46697379,  0.12362084],
       [ 0.95399809, -1.23266407,  1.58244013,  1.68828984, -0.23996986],
       [-1.16599767, -0.62597063,  0.08486272, -0.82618439,  0.85080222],
       [-1.16599767, -1.16416642,  0.30672604, -1.18539499,  0.12362084],
       [ 2.01399597, -0.06820408,  1.5269743 ,  0.61065803,  0.12362084],
       [-0.10599979,  0.1177181 ,  1.08324766, -0.82618439,  1.21439291],
       [-1.16599767, -0.15627249,  0.972316  ,  1.32907923, -1.69433263],
       [-1.16599767,  0.2057865 ,  0.14032855,  0.25144742,  1.5779836 ],
       [-1.16599767, -0.57704374, -1.19085137, -1.5446056 , -0.60356055],
       [ 0.95399809,  1.45831488,  0.4176577 , -0.10776318, -0.96715124],
       [ 0.95399809, -0.51833147,  1.5269743 , -0.10776318, -0.96715124],
       [-0.10599979,  0.27428415, -1.35724886,  1.68828984, -0.60356055],
       [-0.10599979,  0.2057865 , -1.41271469, -0.10776318, -1.33074193],
       [-0.10599979, -0.33240929, -1.5

In [34]:
NB_model = GaussianNB()

In [35]:
NB_model.fit(x_train_scl,y_train)

GaussianNB()

In [36]:
y_pred = NB_model.predict(x_test_scl)

In [37]:
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1])

In [42]:
# Calculating Accuracing score
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy Score :" , accuracy)

Accuracy Score : 0.83


In [44]:
# Classification Report
print(" ==========\n Classification Report ========= ")
print(classification_report(y_test,y_pred))

 Classification Report ========= 
              precision    recall  f1-score   support

           0       0.90      0.75      0.82        51
           1       0.78      0.92      0.84        49

    accuracy                           0.83       100
   macro avg       0.84      0.83      0.83       100
weighted avg       0.84      0.83      0.83       100



In [46]:
NB_model.score(x_test_scl,y_test)

0.83

In [47]:
pd.DataFrame({"y_true": y_test, "y_pred": y_pred})

y_true  y_pred
361       0       1
73        1       0
374       1       1
155       1       1
104       0       0
..      ...     ...
347       0       1
86        0       0
75        0       0
438       0       0
15        1       1

[100 rows x 2 columns]

In [49]:
# Tune hyperparameter
# Define parameter grid for GaussianNB (var_smoothing is the main parameter to tune)

param_grid = {
    'var_smoothing': np.logspace(0, -9, num=10)
}
param_grid

{'var_smoothing': array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
        1.e-08, 1.e-09])}

In [53]:
# Performance grid search
grid_search = GridSearchCV(GaussianNB(), param_grid, cv=5, scoring='accuracy')

grid_search.fit(x_train_scl, y_train)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07,
       1.e-08, 1.e-09])},
             scoring='accuracy')

In [55]:
best_model = grid_search.best_estimator_

print("\n Best Parameter :", grid_search.best_params_)
print("Best Cross_Validation Score: " ,grid_search.best_score_)


 Best Parameter : {'var_smoothing': np.float64(1.0)}
Best Cross_Validation Score:  0.8549999999999999


In [56]:
# Step 9: Evaluate tuned model
# Make predictions with tuned model
y_pred_tunned = best_model.predict(x_test_scl)

In [58]:
tunned_accuracy = accuracy_score(y_test,y_pred_tunned)
tunned_accuracy

0.83

In [59]:
best_model.score(x_test_scl,y_test)

0.83

In [62]:
unseen_data = pd.DataFrame({
    'grade': ['B'],
    'cgpa': [8],
    'iq': [95],
    'communication': [9],
    'technical_knowledge': [6]
})

In [63]:
unseen_data

grade  cgpa  iq  communication  technical_knowledge
0     B     8  95              9                    6

In [64]:
unseen_data["grade"] = le.transform(unseen_data["grade"])
unseen_data_scl = scaler.transform(unseen_data)

In [65]:
unseen_data_scl

array([[-0.10599979,  0.92011909, -0.85805639,  1.32907923,  0.12362084]])

In [68]:
prediction = best_model.predict(unseen_data_scl)
print("\nPrediction for unseen data:", "Placed" if prediction[0] == 1 else "Not Placed")


Prediction for unseen data: Placed


In [69]:
# Conclusion : Model is working properly